DROP TABLE IF EXISTS "accounts";
DROP TABLE IF EXISTS "categories";
DROP TABLE IF EXISTS "gachas";
DROP TABLE IF EXISTS "galleries";
DROP TABLE IF EXISTS "items";
DROP TABLE IF EXISTS "sessions";
DROP TABLE IF EXISTS "users";